spring:
  application:
    name: apiemail
  mail:
    host: smtp.gmail.com
    port: 587
    username: Helpoffice2025@gmail.com
    password: cidh tjhw luzo hsbw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    addresses: amqps://azlgtuxj:HjCUvOPEQhfZBZj-0rVZ_oQFB5ekeDVd@seal.lmq.cloudamqp.com/azlgtuxj
    ssl:
      enabled: true
    queue:
      name: default.security
  datasource:
    url: jdbc:mysql://localhost:3306/ms_email
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka    
  instance:
    instanceId: ${spring.application.name}:${application.instance_id:${random.value}}