spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Rota para API de Funcionário
        - id: apifuncionario
          uri: lb://apifuncionario
          predicates:
            - Path=/funcionario/**
        
        # Rota para API de Segurança
        - id: apisecurity
          uri: lb://apisecurity
          predicates:
            - Path=/auth/**
        
        # Rota para API de HelpDesk
        - id: apihelpdesk
          uri: lb://apihelpdesk
          predicates:
            - Path=/helpdesk/**
        
        # Nova Rota para API de Email
        - id: apiemail
          uri: lb://apiemail  # Nome EXATO registrado no Eureka
          predicates:
            - Path=/email/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${application.instance_id:${random.value}}

api:
  security:
    token:
      secret: cb9404a187ec5b9d9e73af07cb02d13a2c6a24b03469dfb8dad96f84bed1898d